### ISSUE TITLE
Loop infinito al obtener productos 

### ISSUE THREAD

**Issue by KatuGT** [santiagomaza/proyectoFinal-ecomRC-front#2]
![image](https://github.com/santiagomaza/proyectoFinal-ecomRC-front/assets/38865485/60340a9e-aae1-4a77-a8ad-09b530f550f7)

Se hacen peticiones constantemente en el Home y cuando entras a las categorías bebidas y videojuegos,  si no vi mal en  en indumentaria y tecnología no pasa, revisar de todos modos

**Comment by santiagomaza** [comment]
Solucionado problema de loop infinito en páginas home, bebidas y videojuegos
