### ISSUE TITLE
Menu admin - Administración 

### ISSUE THREAD

**Issue by KatuGT** [santiagomaza/proyectoFinal-ecomRC-front#3]
![image](https://github.com/santiagomaza/proyectoFinal-ecomRC-front/assets/38865485/17eae622-af62-4b53-8eae-40a740d5d115)

los enlaces no llevana ningún lado, necesito probar los siguientes puntos expuestos en los requerimientos:

Página de administrador:
El usuario administrador debe poder acceder a una página donde se muestran los listados de usuarios, películas y categorías y además pueda realizar las siguientes operaciones:

Usuarios
Dar de alta Usuarios
○ Inactivar usuarios (Los usuarios inactivos no deben poder loguearse)

Juegos
Dar de alta productos
Modificar productos
Eliminar productos
Marcar como destacado un producto. Sólo los producto destacados se mostrarán en el carrusel de la home page.

Categorías
Dar de alta categorías
Modificar categorías
Eliminar categorías

**Comment by santiagomaza** [comment]
Hola Cintia buenas noches, los enlaces si funcionan, hay que apretar bien en ellos. Intenté de todas maneras de otra forma ya sea con un ancla normal u otro componente de react router dom y en esos casos dejaba de funcionar

**Comment by KatuGT** [comment]
> Hola Cintia buenas noches, los enlaces si funcionan, hay que apretar bien en ellos. Intenté de todas maneras de otra forma ya sea con un ancla normal u otro componente de react router dom y en esos casos dejaba de funcionar

![image](https://github.com/santiagomaza/proyectoFinal-ecomRC-front/assets/38865485/71d8df29-1c52-415f-9d5f-5eb6eec3a5f0)

Santi agregaste un <a> dentro de otro <a> y dependiendo donde hagas click funciona o no, arreglalo porfa

**Comment by santiagomaza** [comment]
Ahora si esta solucionado el problema de navegación
